// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"login-api/domains/users/handlers"
	"login-api/domains/users/repositories"
	"login-api/domains/users/usecases"
	"login-api/routes"
)

// Injectors from injector.go:

func InitializeServer() (*gin.Engine, error) {
	userRepository := repositories.NewUserRepository()
	userUseCase := usecases.NewUserUseCase(userRepository)
	userHttp := handlers.NewUserHttp(userUseCase)
	engine := routes.SetupRoutes(userHttp)
	return engine, nil
}

// injector.go:

var userSet = wire.NewSet(repositories.NewUserRepository, wire.Bind(new(repositories.UserRepositoryInterface), new(*repositories.UserRepository)), usecases.NewUserUseCase, wire.Bind(new(usecases.UserUseCaseInterface), new(*usecases.UserUseCase)), handlers.NewUserHttp, wire.Bind(new(handlers.UserHttpInterface), new(*handlers.UserHttp)))
