// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"payment-service/domains/transaction"
	"payment-service/domains/transaction/repositories"
	"payment-service/domains/transaction/usecases"
	"payment-service/infrastructures"
	"payment-service/infrastructures/messaging"
)

// Injectors from injector.go:

func InitializeApp() (*App, error) {
	postgresDatabase := infrastructures.NewPostgresDatabase()
	transactionRepositoryImpl := repositories.NewTransactionRepository(postgresDatabase)
	transactionUseCaseImpl := usecases.NewTransactionUsecase(postgresDatabase, transactionRepositoryImpl)
	paymentConsumer, err := messaging.NewPaymentConsumer(transactionUseCaseImpl)
	if err != nil {
		return nil, err
	}
	app := NewApp(paymentConsumer, transactionUseCaseImpl)
	return app, nil
}

// injector.go:

type App struct {
	Consumer *messaging.PaymentConsumer
	Usecase  transaction.TransactionUsecase
}

// NewApp is the provider function for the App struct.
func NewApp(consumer *messaging.PaymentConsumer, usecase transaction.TransactionUsecase) *App {
	return &App{Consumer: consumer, Usecase: usecase}
}

var transactionSet = wire.NewSet(repositories.NewTransactionRepository, wire.Bind(new(transaction.TransactionRepository), new(*repositories.TransactionRepositoryImpl)), usecases.NewTransactionUsecase, wire.Bind(new(transaction.TransactionUsecase), new(*usecases.TransactionUseCaseImpl)))

var databaseSet = wire.NewSet(infrastructures.NewPostgresDatabase, wire.Bind(new(infrastructures.Database), new(*infrastructures.PostgresDatabase)))

var messagingSet = wire.NewSet(messaging.NewPaymentConsumer)

var appSet = wire.NewSet(NewApp)
